name: ci
on:
  push:
    branches:    
      - master
    tags:        
      - v2.*
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: install nginx
        run: ls
#        run: sudo apt install nginx -y
      -
        name: Check nginx config
        run: nginx -t -c $PWD/nginx.conf
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
