name: ci
on:
  push:
    branches:
      - master
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - 
        name: Install Nginx
        run: sudo apt install nginx -y
      -
	name: Test conf
	run: sudo nginx -t -c ./nginx.conf
