name: ci
on:
  push:
    branches:
      - old-one
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: sudo apt install nginx -y
       - run: ls /home/runner/work/Checker-nginx-config-CI-CD-/Checker-nginx-config-CI-CD-
#       - run: sudo nginx -t -c home/runner/work/Checker-nginx-config-CI-CD-/Checker-nginx-config-CI-CD-/.github/workflows/nginx.conf
