name: ci
on:
  push:
    branches:
      - old-one
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: sudo apt install nginx -y
       - run: sudo nginx -t -c ./nginx.conf
